name: Sync appVersion
on:
  pull_request:
    paths:
      - "values.yaml"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Sync appVersion
        run: .github/sync-appversion.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Chart.yaml
          git commit -m "chore: sync appVersion from values.yaml" || echo "No changes"
          git push
